/**
 * 单点登录
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * @property `[bizBody]`
 * @property `[nonestr]`
 * @property `[page]`
 * @property `[timestamp]`
 */
export interface RequestParamBodyUserLoginReqVO {
  bizBody?: models.UserLoginReqVO;
  nonestr?: string;
  page?: models.RequestPageInfo;
  timestamp?: number;
}
