/**
 * 单点登录
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * @property `[bizBody]`
 * @property `[code]`
 * @property `[msg]`
 * @property `[paging]`
 * @property `[timestamp]`
 */
export interface ResultBody {
  bizBody?: any;
  code?: number;
  msg?: models.ResultMessage;
  paging?: models.ResultPageInfo;
  timestamp?: number;
}
