/**
 * 单点登录
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * @property `[alert]`
 * @property `[content]`
 * @property `[stackTrace]`
 */
export interface ResultMessage {
  alert?: string;
  content?: string;
  stackTrace?: string;
}
