/**
 * 单点登录
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * @property `dingUnionid` 钉钉用户标识
 * @property `operAccount` 账户名
 * @property `token` 账户密码
 */
export interface UserLoginResVO {
  /**
   * 钉钉用户标识
   */
  dingUnionid: string;
  /**
   * 账户名
   */
  operAccount: string;
  /**
   * 账户密码
   */
  token: string;
}
